// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdg1kvmNhZZhLjRaUWDZPVeq7f-eGUZGc',
    appId: '1:1087417071201:web:8ee7cef51863d10564dc20',
    messagingSenderId: '1087417071201',
    projectId: 'narangavellam-stg-86763',
    authDomain: 'narangavellam-stg-86763.firebaseapp.com',
    storageBucket: 'narangavellam-stg-86763.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArVKEUu__3fiwVX-aJsYSUOUHgjVaOWVQ',
    appId: '1:1087417071201:android:d49fd2202b13993a64dc20',
    messagingSenderId: '1087417071201',
    projectId: 'narangavellam-stg-86763',
    storageBucket: 'narangavellam-stg-86763.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7aJLUnv5wZuNtD_f7slJOBfkefvr91Mw',
    appId: '1:1087417071201:ios:4c1ae40c1913b55564dc20',
    messagingSenderId: '1087417071201',
    projectId: 'narangavellam-stg-86763',
    storageBucket: 'narangavellam-stg-86763.firebasestorage.app',
    iosClientId: '1087417071201-k1hdpin40787uk4bi6vhos6n5flg7pgk.apps.googleusercontent.com',
    iosBundleId: 'com.narangavellam.narangavellam.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7aJLUnv5wZuNtD_f7slJOBfkefvr91Mw',
    appId: '1:1087417071201:ios:4c1ae40c1913b55564dc20',
    messagingSenderId: '1087417071201',
    projectId: 'narangavellam-stg-86763',
    storageBucket: 'narangavellam-stg-86763.firebasestorage.app',
    iosClientId: '1087417071201-k1hdpin40787uk4bi6vhos6n5flg7pgk.apps.googleusercontent.com',
    iosBundleId: 'com.narangavellam.narangavellam.stg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdg1kvmNhZZhLjRaUWDZPVeq7f-eGUZGc',
    appId: '1:1087417071201:web:1886621856099bbb64dc20',
    messagingSenderId: '1087417071201',
    projectId: 'narangavellam-stg-86763',
    authDomain: 'narangavellam-stg-86763.firebaseapp.com',
    storageBucket: 'narangavellam-stg-86763.firebasestorage.app',
  );
}
