// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWmy6DrC7dbUq_WxhHcbRD6I1A1G-qfow',
    appId: '1:251711139469:web:5bfaedbd31b0b753cf3cc4',
    messagingSenderId: '251711139469',
    projectId: 'narangavellam-prod-c4f15',
    authDomain: 'narangavellam-prod-c4f15.firebaseapp.com',
    storageBucket: 'narangavellam-prod-c4f15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Xj8SpypRV5nL3sM623Nu44UwC-u2VYU',
    appId: '1:251711139469:android:1dfb89ed63a48638cf3cc4',
    messagingSenderId: '251711139469',
    projectId: 'narangavellam-prod-c4f15',
    storageBucket: 'narangavellam-prod-c4f15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvBEmoO81Nnyux-gzUAzPt6mzOUKHv72o',
    appId: '1:251711139469:ios:73ade8605c7fc1f8cf3cc4',
    messagingSenderId: '251711139469',
    projectId: 'narangavellam-prod-c4f15',
    storageBucket: 'narangavellam-prod-c4f15.firebasestorage.app',
    iosClientId: '251711139469-mvefk5eveof3q38m33nkb2ar8cmisc8l.apps.googleusercontent.com',
    iosBundleId: 'com.narangavellam.narangavellam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWmy6DrC7dbUq_WxhHcbRD6I1A1G-qfow',
    appId: '1:251711139469:web:ea893725d613a4d7cf3cc4',
    messagingSenderId: '251711139469',
    projectId: 'narangavellam-prod-c4f15',
    authDomain: 'narangavellam-prod-c4f15.firebaseapp.com',
    storageBucket: 'narangavellam-prod-c4f15.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvBEmoO81Nnyux-gzUAzPt6mzOUKHv72o',
    appId: '1:251711139469:ios:73ade8605c7fc1f8cf3cc4',
    messagingSenderId: '251711139469',
    projectId: 'narangavellam-prod-c4f15',
    storageBucket: 'narangavellam-prod-c4f15.firebasestorage.app',
    iosClientId: '251711139469-mvefk5eveof3q38m33nkb2ar8cmisc8l.apps.googleusercontent.com',
    iosBundleId: 'com.narangavellam.narangavellam',
  );

}