// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC86_ES3RmRqjqGvKcTUUbFSfXZQX6njpY',
    appId: '1:676095049215:web:116a34174b02779b29bbca',
    messagingSenderId: '676095049215',
    projectId: 'narangavellam-dev-c8eb7',
    authDomain: 'narangavellam-dev-c8eb7.firebaseapp.com',
    storageBucket: 'narangavellam-dev-c8eb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb2V80Las1rYiJOUZjPrYYHzZ6E95WtBs',
    appId: '1:676095049215:android:3423f807f30ab22a29bbca',
    messagingSenderId: '676095049215',
    projectId: 'narangavellam-dev-c8eb7',
    storageBucket: 'narangavellam-dev-c8eb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiRjH00y1DTNLi-uYwe1jCQUeLGEaiA0c',
    appId: '1:676095049215:ios:f9ccacb954ba1cd029bbca',
    messagingSenderId: '676095049215',
    projectId: 'narangavellam-dev-c8eb7',
    storageBucket: 'narangavellam-dev-c8eb7.firebasestorage.app',
    iosClientId: '676095049215-hma6da6ikimbuoqcgrqcgvbir6f996bf.apps.googleusercontent.com',
    iosBundleId: 'com.narangavellam.narangavellam.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiRjH00y1DTNLi-uYwe1jCQUeLGEaiA0c',
    appId: '1:676095049215:ios:f9ccacb954ba1cd029bbca',
    messagingSenderId: '676095049215',
    projectId: 'narangavellam-dev-c8eb7',
    storageBucket: 'narangavellam-dev-c8eb7.firebasestorage.app',
    iosClientId: '676095049215-hma6da6ikimbuoqcgrqcgvbir6f996bf.apps.googleusercontent.com',
    iosBundleId: 'com.narangavellam.narangavellam.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC86_ES3RmRqjqGvKcTUUbFSfXZQX6njpY',
    appId: '1:676095049215:web:98b66bd82be8a75a29bbca',
    messagingSenderId: '676095049215',
    projectId: 'narangavellam-dev-c8eb7',
    authDomain: 'narangavellam-dev-c8eb7.firebaseapp.com',
    storageBucket: 'narangavellam-dev-c8eb7.firebasestorage.app',
  );
}
